import {HeaderMenu} from "../components/HeaderMenu/HeaderMenu";
import ContactForm from "@/components/ContactForm/ContactForm";
import {Text, Title} from "@mantine/core";

export default function ContactPage() {
    return (
        <>
            <HeaderMenu />
            <Title ta={'center'} order={1}>Battery storage</Title>
            <Title ta={'center'} order={3} m={'lg'}>Entry Level Storage Solution</Title>
            <Text color="dimmed" ta="center" size="lg" maw={580} mx="auto" mt="xl">
                Installing battery storage paired with solar PV systems offers several benefits. Firstly, it allows for energy independence by storing excess solar power generated during the day for use at night or during cloudy periods. This can reduce reliance on the grid, leading to potential cost savings and increased resilience during power outages. Additionally, battery storage can help optimise energy usage by enabling homeowners to shift their energy consumption to times when electricity costs are lower. Overall, the combination of solar PV and battery storage can enhance sustainability, reduce electricity bills, and provide a reliable power source.
            </Text>
            <Text color="dimmed" ta="center" size="lg" maw={580} mx="auto" mt="xl">
                This Lithium-ion option offers a compact energy storage solution if space is an issue and you still want to hold on to that energy generated from your solar PV panels.
            </Text>
            <Title ta={'center'} order={3} m={'lg'}>Off-Grid Solution</Title>
            <Text color="dimmed" ta="center" size="lg" maw={580} mx="auto" mt="xl">
                AGM batteries are a popular choice for solar storage due to their affordability, reliability, and proven technology. They are efficient at storing energy generated by solar panels, making them a cost-effective option for residential and commercial use. Additionally, AGM batteries are readily available, easy to install, and have a long lifecycle with zero maintenance, providing a dependable energy storage solution for solar power systems.
            </Text>
            <Text color="dimmed" ta="center" size="lg" maw={580} mx="auto" mt="xl">
                This AGM option is a more affordable way to store your home-grown energy, with the drawback being that it takes up more space therefor a garage or covered area is highly recommended first.
            </Text>

            <Title ta={'center'} order={3} m={'xl'}>Enter below to get a free savings estimate.</Title>

            <ContactForm />


        </>
    );
}
